// Scrape results for March 9-15, 2026 NYC Events
// Sources: Metrograph, Film Forum, IFC Center, Lincoln Center, The Met, MoMA, Time Out, doNYC

const filmMuseumEvents = {
  weekOf: "2026-03-09",
  events: [
    // METROGRAPH FILMS (Source 1)
    { id: "metrograph-1", title: "Paris, Texas", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999000581", description: "Wim Wenders / 1984 / 145min / DCP", price: null },
    { id: "metrograph-2", title: "By The Time It Gets Dark", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999002975", description: "Anocha Suwichakornpong / 2016 / 105min / DCP. Q&A with director on Sunday, February 22nd", price: null },
    { id: "metrograph-3", title: "Klute", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999000329", description: "Alan J. Pakula / 1971 / 114min / 35mm", price: null },
    { id: "metrograph-4", title: "Diary of a Country Priest", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999000872", description: "Robert Bresson / 1951 / 115min / DCP", price: null },
    { id: "metrograph-5", title: "The Holy Girl", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004705", description: "Lucrecia Martel / 2004 / 106min / 35mm. Part of Sex is Confusion series", price: null },
    { id: "metrograph-6", title: "Irma Vep", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999000516", description: "Olivier Assayas / 1996 / 99min / DCP", price: null },
    { id: "metrograph-7", title: "Pinocchio", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004730", description: "Wilfred Jackson, Norman T. Ferguson, T. Hee / 1940 / 88min / 35mm IB-Technicolor print courtesy of Library of Congress", price: null },
    { id: "metrograph-8", title: "The Player", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999003399", description: "Robert Altman / 1992 / 124min / DCP", price: null },
    { id: "metrograph-9", title: "Inland Empire", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004189", description: "David Lynch / 2006 / 180min / 4K DCP", price: null },
    { id: "metrograph-10", title: "Stalker", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999001012", description: "Andrei Tarkovsky / 1979 / 163min / DCP", price: null },
    { id: "metrograph-11", title: "Downtown 81", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999002127", description: "Edo Bertoglio / 2000 / 75min / DCP", price: null },
    { id: "metrograph-12", title: "Raise the Red Lantern", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004742", description: "Yimou Zhang / 1991 / 125min / 35mm", price: null },
    { id: "metrograph-13", title: "Dead Man", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999000299", description: "Jim Jarmusch / 1995 / 121min / DCP", price: null },
    { id: "metrograph-14", title: "Clouds of Sils Maria", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999002785", description: "Olivier Assayas / 2014 / 124min / DCP", price: null },
    { id: "metrograph-15", title: "Made in Hong Kong", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999002313", description: "Fruit Chan / 1997 / 108min / DCP", price: null },
    { id: "metrograph-16", title: "Point Blank", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999000587", description: "John Boorman / 1967 / 92min / 35mm", price: null },
    { id: "metrograph-17", title: "Mundane History", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004711", description: "Anocha Suwichakornpong film with Q&A with the filmmaker", price: null },
    { id: "metrograph-18", title: "Krabi 2562", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004710", description: "Anocha Suwichakornpong film with Q&A with the filmmaker", price: null },
    { id: "metrograph-19", title: "A Real Young Girl", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004706", description: "Catherine Breillat film. Part of Sex is Confusion series", price: null },
    { id: "metrograph-20", title: "The Most Terrible Time in My Life", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004728", description: "Kaizo Hayashi / 1993 / 92min / 4K DCP", price: null },
    { id: "metrograph-21", title: "The Stairway to a Distant Past", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004729", description: "Kaizo Hayashi / 1995 / 101min / 4K DCP", price: null },
    { id: "metrograph-22", title: "The Trap", venue: "Metrograph", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://metrograph.com/film/?vista_film_id=9999004734", description: "Kaizo Hayashi / 1996 / 106min / 4K DCP", price: null },

    // FILM FORUM (Source 2) - Limited data from static fetch
    { id: "filmforum-1", title: "Film Forum Programming", venue: "Film Forum", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://filmforum.org/now_playing", description: "Independent and repertory cinema - check website for current schedule. All films projected on DCP unless otherwise noted.", price: null },

    // IFC CENTER (Source 3)
    { id: "ifc-1", title: "Animated Oscar-Nominated Shorts 2026", venue: "IFC Center", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.ifccenter.com/films/animated-oscar-nominated-shorts-2026/", description: "Academy Award-nominated animated short films", price: null },
    { id: "ifc-2", title: "Live-Action Oscar-Nominated Shorts 2026", venue: "IFC Center", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.ifccenter.com/films/live-action-oscar-nominated-shorts-2026/", description: "Academy Award-nominated live-action short films", price: null },
    { id: "ifc-3", title: "Doc Program A: Oscar-Nominated Shorts 2026", venue: "IFC Center", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.ifccenter.com/films/doc-program-a-oscar-nominated-shorts-2026/", description: "Academy Award-nominated documentary shorts", price: null },
    { id: "ifc-4", title: "Doc Program B: Oscar-Nominated Shorts 2026", venue: "IFC Center", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.ifccenter.com/films/doc-program-b-oscar-nominated-shorts-2026/", description: "Academy Award-nominated documentary shorts", price: null },
    { id: "ifc-5", title: "Nirvanna: The Band The Show The Movie", venue: "IFC Center", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.ifccenter.com/films/nirvanna-the-band-the-show-the-movie/", description: "Matt Johnson comedy - now playing", price: null },
    { id: "ifc-6", title: "Pictures of Ghosts", venue: "IFC Center", date: "2026-03-09", time: "7:00 PM", category: "Film", sourceUrl: "https://www.ifccenter.com/films/pictures-of-ghosts/", description: "Kleber Mendonça Filho documentary about cinema & memory. Filmmaker in person on Mon, Mar 2", price: null },
    { id: "ifc-7", title: "Sirat", venue: "IFC Center", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.ifccenter.com/films/sirat/", description: "Directed by Oliver Laxe. Q&A with director Mon, Mar 2 at 7:15 show. Academy Award Nominee: Best International Feature Film & Best Sound", price: null },
    { id: "ifc-8", title: "DOC NYC Selects: A Life Illuminated", venue: "IFC Center", date: "2026-03-10", time: "7:00 PM", category: "Film", sourceUrl: "https://www.ifccenter.com/films/a-life-illuminated/", description: "DOC NYC Selects series with filmmaker Q&A on Tue, Mar 3", price: null },
    { id: "ifc-9", title: "The Ugly Stepsister", venue: "IFC Center", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.ifccenter.com/films/the-ugly-stepsister/", description: "Academy Award Nominee: Best Makeup and Hairstyling. 35mm print on Wed, Mar 4 at 7:00", price: null },
    { id: "ifc-10", title: "Dolly", venue: "IFC Center", date: "2026-03-12", time: "7:00 PM", category: "Film", sourceUrl: "https://www.ifccenter.com/films/dolly/", description: "Screening on 35mm followed by Q&A with star Ethan Suplee on Thu, Mar 5. Part of Shudder Showcase", price: null },
    { id: "ifc-11", title: "Miroirs No. 3", venue: "IFC Center", date: "2026-03-19", time: "7:40 PM", category: "Film", sourceUrl: "https://www.ifccenter.com/films/miroirs-no-3/", description: "Q&As with dir. Christian Petzold Thu, Mar 19-Sat, Mar 21. Opens Fri, Mar 20", price: null },
    { id: "ifc-12", title: "Dead Lover", venue: "IFC Center", date: "2026-03-19", time: "7:00 PM", category: "Film", sourceUrl: "https://www.ifccenter.com/films/dead-lover/", description: "Q&As with filmmakers Grace Glowicki & Ben Petrie Thu, Mar 19-Sun, Mar 22. Opens Fri, Mar 20", price: null },

    // LINCOLN CENTER (Source 4)
    { id: "lincoln-1", title: "Doc Fortnight Shorts 2: Sight Lines", venue: "Film at Lincoln Center", date: "2026-03-09", time: "4:30 PM", category: "Film", sourceUrl: "https://www.filmlinc.org/films/doc-fortnight-shorts-2-sight-lines/", description: "Followed by a conversation with Mike Stoltz and Rhea Storr", price: null },
    { id: "lincoln-2", title: "An Evening with Mark Jenkin", venue: "Film at Lincoln Center", date: "2026-03-09", time: "7:00 PM", category: "Film", sourceUrl: "https://www.filmlinc.org/", description: "Special filmmaker evening", price: null },
    { id: "lincoln-3", title: "Ragtime", venue: "Lincoln Center Theater", date: "2026-03-09", time: "7:00 PM", category: "Theater", sourceUrl: "https://lct.org/shows/ragtime/", description: "Broadway musical", price: null },
    { id: "lincoln-4", title: "Night Side Songs", venue: "Lincoln Center Theater", date: "2026-03-09", time: "8:00 PM", category: "Theater", sourceUrl: "https://lct.org/shows/night-side-songs/", description: "Theatrical performance", price: null },
    { id: "lincoln-5", title: "CMS Kids III", venue: "Chamber Music Society of Lincoln Center", date: "2026-03-14", time: "11:00 AM", category: "Music", sourceUrl: "https://www.chambermusicsociety.org/our-concerts/at-lincoln-center/family-programs/25-26/cms-kids-iii/", description: "Family chamber music program", price: null },
    { id: "lincoln-6", title: "Gražinytė-Tyla Conducts Elgar & Schumann", venue: "New York Philharmonic", date: "2026-03-13", time: "7:30 PM", category: "Music", sourceUrl: "https://www.nyphil.org/concerts-tickets/2526/grazinyte-tyla-conducts-elgar-and-schumann/", description: "Classical concert", price: null },
    { id: "lincoln-7", title: "Othello", venue: "American Ballet Theatre", date: "2026-03-13", time: "7:30 PM", category: "Dance", sourceUrl: "https://www.abt.org/", description: "Ballet performance at David H. Koch Theater", price: null },
    { id: "lincoln-8", title: "Transa Rising: Lambkin", venue: "Lincoln Center Presents", date: "2026-03-12", time: "7:30 PM", category: "Music", sourceUrl: "https://www.lincolncenter.org/series/lincoln-center-presents/transa-rising-lambkin-600", description: "Contemporary music performance", price: null },
    { id: "lincoln-9", title: "Transa Rising: Benét", venue: "Lincoln Center Presents", date: "2026-03-13", time: "7:30 PM", category: "Music", sourceUrl: "https://www.lincolncenter.org/series/lincoln-center-presents/transa-rising-benet-689", description: "Contemporary music performance", price: null },
    { id: "lincoln-10", title: "cOsmO", venue: "Lincoln Center Presents", date: "2026-03-14", time: "11:00 AM", category: "Family", sourceUrl: "https://www.lincolncenter.org/series/lincoln-center-presents/cosmo-26", description: "Kids & Family Program", price: null },
    { id: "lincoln-11", title: "Inua Ellams: Falling Into You R.A.P. Party", venue: "Lincoln Center Presents", date: "2026-03-14", time: "7:30 PM", category: "Music", sourceUrl: "https://www.lincolncenter.org/series/lincoln-center-presents/inua-ellams-lessemgreaterfalling-into-youlessemgreater-rap-party-623", description: "Spoken word and music performance", price: null },
    { id: "lincoln-12", title: "Sonic Spectrum III", venue: "Chamber Music Society of Lincoln Center", date: "2026-03-12", time: "7:30 PM", category: "Music", sourceUrl: "https://www.chambermusicsociety.org/our-concerts/at-lincoln-center/events/25-26/sonic-spectrum-iii/", description: "Contemporary chamber music", price: null },
    { id: "lincoln-13", title: "Big Band Afrobeat to Afrobeats: Ulysses Owens Jr. with Michael Olatuja", venue: "Jazz at Lincoln Center", date: "2026-03-13", time: "7:00 PM", category: "Music", sourceUrl: "https://ticketing.jazz.org/18802/18803", description: "Jazz concert", price: null },
    { id: "lincoln-14", title: "Family Concert: Who is Louis Armstrong?", venue: "Jazz at Lincoln Center", date: "2026-03-14", time: "1:00 PM", category: "Family", sourceUrl: "https://ticketing.jazz.org/18617/18618", description: "Jazz at Lincoln Center Orchestra family program", price: null },
    { id: "lincoln-15", title: "Masters At Work III", venue: "New York City Ballet", date: "2026-03-14", time: "3:00 PM", category: "Dance", sourceUrl: "https://www.nycballet.com/season-and-tickets/winter-2026/masters-at-work-iii/", description: "Ballet program", price: null },

    // THE MET (Source 5)
    { id: "met-1", title: "Featured Exhibitions", venue: "The Metropolitan Museum of Art", date: "2026-03-09", time: "10:00 AM - 5:00 PM", category: "Museum", sourceUrl: "https://www.metmuseum.org/exhibitions", description: "5 featured exhibitions on display. Museum open daily with various temporary and permanent exhibitions including works by Van Gogh, Degas, Vermeer, Rembrandt, Monet and more.", price: "Pay-what-you-wish for NY residents" },
    { id: "met-2", title: "Recently Opened Exhibitions", venue: "The Metropolitan Museum of Art", date: "2026-03-09", time: "10:00 AM - 5:00 PM", category: "Museum", sourceUrl: "https://www.metmuseum.org/exhibitions", description: "3 recently opened exhibitions on display", price: "Pay-what-you-wish for NY residents" },
    { id: "met-3", title: "Closing Soon", venue: "The Metropolitan Museum of Art", date: "2026-03-09", time: "10:00 AM - 5:00 PM", category: "Museum", sourceUrl: "https://www.metmuseum.org/exhibitions", description: "5 exhibitions closing soon - don't miss them", price: "Pay-what-you-wish for NY residents" },
    { id: "met-4", title: "More Temporary Exhibitions", venue: "The Metropolitan Museum of Art", date: "2026-03-09", time: "10:00 AM - 5:00 PM", category: "Museum", sourceUrl: "https://www.metmuseum.org/exhibitions", description: "10 additional temporary exhibitions on view", price: "Pay-what-you-wish for NY residents" },

    // MOMA (Source 6)
    { id: "moma-1", title: "Doc Fortnight Shorts 2: Sight Lines", venue: "MoMA", date: "2026-03-09", time: "4:30 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11247", description: "Film screening followed by conversation with Mike Stoltz and Rhea Storr. MoMA, Floor T2/T1", price: null },
    { id: "moma-2", title: "An Evening with Mark Jenkin", venue: "MoMA", date: "2026-03-09", time: "7:00 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11245", description: "Special filmmaker evening. MoMA, Floor T2/T1", price: null },
    { id: "moma-3", title: "Prime Time Studio Workshop: Modern Marks", venue: "MoMA", date: "2026-03-10", time: "1:00 PM", category: "Workshop", sourceUrl: "https://www.moma.org/calendar/events/11184", description: "Workshop for visitors 65 and over. Education Center, Mezzanine", price: null },
    { id: "moma-4", title: "Doc Fortnight Shorts 3: Back to Earth", venue: "MoMA", date: "2026-03-15", time: "2:00 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11248", description: "Followed by conversation with Xiao Zhang. MoMA, Floor T2/T1", price: null },
    { id: "moma-5", title: "As Estações (The Seasons)", venue: "MoMA", date: "2026-03-15", time: "2:30 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11233", description: "Directed by Maureen Fazendeiro. MoMA, Floor T2/T1", price: null },
    { id: "moma-6", title: "EIGHT BRIDGES", venue: "MoMA", date: "2026-03-15", time: "4:30 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11236", description: "Directed by James Benning. Followed by conversation with James Benning. MoMA, Floor T2/T1", price: null },
    { id: "moma-7", title: "Matter of Britain", venue: "MoMA", date: "2026-03-05", time: "7:00 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11237", description: "Directed by Peter Treherne. Followed by conversation with Peter Treherne", price: null },
    { id: "moma-8", title: "Powwow People", venue: "MoMA", date: "2026-03-03", time: "4:00 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11241", description: "Directed by Sky Hopinka", price: null },
    { id: "moma-9", title: "甘露水 (Daughter of Nectar)", venue: "MoMA", date: "2026-03-03", time: "6:30 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11235", description: "Directed by Pang-Chuan Huang, Chunni Lin", price: null },
    { id: "moma-10", title: "Cara a Cara (Face to Face)", venue: "MoMA", date: "2026-03-03", time: "7:00 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11234", description: "Directed by Federico Veiroj", price: null },
    { id: "moma-11", title: "Narrative / โลคอลเซนซ์ชันส์ (Local Sensations)", venue: "MoMA", date: "2026-03-05", time: "4:30 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11239", description: "Directed by Anocha Suwichakornpong and Tulapop Saenjaroen. Introduced by Anocha Suwichakornpong", price: null },
    { id: "moma-12", title: "Noghteh-e-Goriz (The Vanishing Point)", venue: "MoMA", date: "2026-03-07", time: "7:00 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11240", description: "Directed by Bani Khoshnoudi. Followed by conversation with Bani Khoshnoudi", price: null },
    { id: "moma-13", title: "Tycoon", venue: "MoMA", date: "2026-03-07", time: "7:00 PM", category: "Film", sourceUrl: "https://www.moma.org/calendar/events/11244", description: "Directed by Charlotte Zhang. Followed by conversation with Charlotte Zhang", price: null },
    { id: "moma-14", title: "UNIQLO Friday Nights", venue: "MoMA", date: "2026-03-06", time: "5:30 PM", category: "Gallery Experience", sourceUrl: "https://www.moma.org/calendar/events/10253", description: "Gallery experience 5:30-8:30 PM", price: "Free for NYers" },
    { id: "moma-15", title: "Member Early Hour", venue: "MoMA", date: "2026-03-07", time: "9:30 AM", category: "Gallery Experience", sourceUrl: "https://www.moma.org/calendar/events/7435", description: "Early access for members 9:30-10:30 AM", price: "Members only" },
  ]
};

const generalEvents = {
  weekOf: "2026-03-09",
  events: [
    // TIME OUT NEW YORK (Source 7)
    { id: "timeout-1", title: "Flamenco Festival", venue: "Multiple NYC Venues", date: "2026-03-09", time: "Various", category: "Dance", sourceUrl: "https://www.timeout.com/newyork/dance/flamenco-festival-2025", description: "25th edition showcasing Spanish flamenco at a dozen NYC venues including City Center, Jazz at Lincoln Center, Joe's Pub. 80+ participants from 16 companies through March 15.", price: "Various" },
    { id: "timeout-2", title: "Reopening of Hudson Yards - The Vessel", venue: "Hudson Yards", date: "2026-03-09", time: "11:00 AM - 7:00 PM", category: "Attraction", sourceUrl: "https://www.timeout.com/newyork/news/the-infamous-vessel-at-hudson-yards-is-reopening-in-four-days-022326", description: "The 150-foot honeycomb structure reopens. NYC residents get free Thursday reservations with ID.", price: "Free for residents Thu, tickets required" },
    { id: "timeout-3", title: "You Got Older", venue: "Cherry Lane Theatre", date: "2026-03-09", time: "Various", category: "Theater", sourceUrl: "https://www.timeout.com/newyork/theater/you-got-older-review-revival-alia-shawkat-peter-friedman-clare-barron", description: "Alia Shawkat stars in Clare Barron's Off-Broadway play at A24's Cherry Lane Theatre", price: null },
    { id: "timeout-4", title: "New York International Children's Film Festival", venue: "IFC Center, SVA, Scandinavia House", date: "2026-03-09", time: "Various", category: "Film", sourceUrl: "https://www.timeout.com/newyork/movies/new-york-international-childrens-film-festival-1", description: "30th edition through March 16. Opening: Disney & Pixar's HOPPER, Centerpiece: Remaining Native documentary, U.S. premiere: My Life in Versailles animated short.", price: null },
    { id: "timeout-5", title: "Outwit, Outplay, Outlast: Celebrating 50 Seasons of Survivor", venue: "Paley Center", date: "2026-03-09", time: "Various", category: "Exhibition", sourceUrl: "https://www.timeout.com/newyork/news/this-new-exhibit-celebrates-50-seasons-of-survivor-with-behind-the-scenes-videos-and-more-012326", description: "Immersive Survivor exhibit through May 31. Features outfits, immunity idols, torch snuffer, original sketches, and screenings.", price: null },
    { id: "timeout-6", title: "Dance Reflections by Van Cleef & Arpels Festival", venue: "BAM, Joyce Theater, NY Live Arts, City Center", date: "2026-03-09", time: "Various", category: "Dance", sourceUrl: "https://www.timeout.com/newyork/things-to-do/dance-reflections-by-van-clef-arpels-festival", description: "Five-week festival exploring dance across generations. Features Merce Cunningham, Trisha Brown, Anne Teresa De Keersmaeker, Benjamin Millepied, and more.", price: null },
    { id: "timeout-7", title: "Ballet Photography Exhibition", venue: "Leica Gallery New York", date: "2026-03-09", time: "Various", category: "Art", sourceUrl: "https://www.timeout.com/newyork/things-to-do/ballet-at-leica-gallery-new-york", description: "Never-before-seen photographs of Misty Copeland in her final ABT performance. Running through March 29.", price: "Free" },
    { id: "timeout-8", title: "Every Brilliant Thing", venue: "Broadway", date: "2026-03-09", time: "Various", category: "Theater", sourceUrl: "https://www.timeout.com/newyork/theater/every-brilliant-thing-1", description: "Daniel Radcliffe in Broadway premiere of Duncan Macmillan's interactive dark comedy", price: null },
    { id: "timeout-9", title: "Ringling Bros. and Barnum & Bailey", venue: "Barclays Center / UBS Arena", date: "2026-03-14", time: "Various", category: "Circus", sourceUrl: "https://www.timeout.com/newyork/news/the-circus-is-back-in-town-012226", description: "The Greatest Show on Earth returns - all-human spectacle. Barclays Center Feb 19-22, UBS Arena March 6-8", price: null },

    // DONYC EVENTS (Source 8) - March 9
    { id: "donyc-m9-1", title: "Gabi Hartmann", venue: "Le Poisson Rouge", date: "2026-03-09", time: "7:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/gabi-hartmann-tickets", description: "Live music performance at LPR", price: null },
    { id: "donyc-m9-2", title: "Lykn", venue: "Music Hall of Williamsburg", date: "2026-03-09", time: "5:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/lykn-tickets", description: "Live performance", price: null },
    { id: "donyc-m9-3", title: "NYC Barz Exam: Karl Dice Raw Jenkins + more", venue: "Mercury Lounge", date: "2026-03-09", time: "6:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/nyc-barz-exam-karl-dice-raw-jenkins-more-tickets", description: "Hip hop showcase", price: null },
    { id: "donyc-m9-4", title: "Mitski - Nothing's About to Happen to Me", venue: "The Shed", date: "2026-03-09", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/mitski-tickets", description: "Mitski live performance", price: null },
    { id: "donyc-m9-5", title: "The Moth Storyslam", venue: "The Bell House", date: "2026-03-09", time: "8:00 PM", category: "Storytelling", sourceUrl: "https://donyc.com/events/2026/3/9/the-moth-storyslam-tickets", description: "Live storytelling competition", price: null },
    { id: "donyc-m9-6", title: "The Legion Of Skanks Podcast Live", venue: "The Stand", date: "2026-03-09", time: "8:00 PM", category: "Comedy", sourceUrl: "https://donyc.com/events/2026/3/9/the-legion-of-skanks-podcast-live-tickets", description: "Live podcast recording", price: null },
    { id: "donyc-m9-7", title: "Jam Session Hosted By Adam Ray", venue: "Smalls Jazz Club", date: "2026-03-09", time: "11:45 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/jam-session-hosted-by-adam-ray-tickets", description: "Late night jazz jam", price: null },
    { id: "donyc-m9-8", title: "piri & tommy", venue: "Baby's All Right", date: "2026-03-09", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/piri-tommy-tickets", description: "Live performance", price: null },
    { id: "donyc-m9-9", title: "Rev. Vince Anderson & The Love Choir!", venue: "Union Pool", date: "2026-03-09", time: "8:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/rev-vince-anderson-the-love-choir-tickets", description: "Free weekly show", price: "Free" },
    { id: "donyc-m9-10", title: "Brooklyn Nets vs. Memphis Grizzlies", venue: "Barclays Center", date: "2026-03-09", time: "7:30 PM", category: "Sports", sourceUrl: "https://donyc.com/events/2026/3/9/brooklyn-nets-vs-memphis-grizzlies-tickets", description: "NBA basketball game", price: null },
    { id: "donyc-m9-11", title: "Dizzy Gillespie All-Stars", venue: "Blue Note Jazz Club", date: "2026-03-09", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/dizzy-gillespie-all-stars-tickets", description: "Jazz performance", price: null },
    { id: "donyc-m9-12", title: "Golden Classical Music Awards Ceremony", venue: "Carnegie Hall", date: "2026-03-09", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/9/golden-classical-music-awards-ceremony-tickets", description: "Classical music awards", price: null },
    
    // DONYC EVENTS (Source 8) - March 10
    { id: "donyc-m10-1", title: "missed connections with girls", venue: "Good Judy", date: "2026-03-10", time: "7:00 PM", category: "Comedy", sourceUrl: "https://donyc.com/events/2026/3/10/missed-connections-with-girls-tickets", description: "Free comedy show", price: "Free" },
    { id: "donyc-m10-2", title: "Chris Dave X Dj Jazzy Jeff X Savion Glover", venue: "Blue Note Jazz Club", date: "2026-03-10", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/chris-dave-x-dj-jazzy-jeff-x-savion-glover-tickets", description: "Special collaboration performance", price: null },
    { id: "donyc-m10-3", title: "Josman", venue: "Le Poisson Rouge", date: "2026-03-10", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/josman-tickets", description: "Live performance", price: null },
    { id: "donyc-m10-4", title: "Tedeschi Trucks Band", venue: "Beacon Theatre", date: "2026-03-10", time: "7:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/tedeschi-trucks-band-tickets", description: "Blues rock concert", price: null },
    { id: "donyc-m10-5", title: "Six Organs of Admittance + Mark Morgan", venue: "Union Pool", date: "2026-03-10", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/free-six-organs-of-admittance-mark-morgan-tickets", description: "Free show presented by Union Pool", price: "Free" },
    { id: "donyc-m10-6", title: "Rainbow Kitten Surprise: bones North American Tour", venue: "Brooklyn Paramount", date: "2026-03-10", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/rainbow-kitten-surprise-bones-north-american-tour-tickets", description: "Indie rock concert", price: null },
    { id: "donyc-m10-7", title: "Chasing Abbey", venue: "Mercury Lounge / Bowery Ballroom", date: "2026-03-10", time: "6:00 PM / 7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/chasing-abbey-tickets", description: "Double performance", price: null },
    { id: "donyc-m10-8", title: "Bad Omens: Do You Feel Love North American Tour", venue: "Prudential Center", date: "2026-03-10", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/bad-omens-do-you-feel-love-north-american-tour-tickets", description: "Metal concert in Newark", price: null },
    { id: "donyc-m10-9", title: "Saxsquatch, Electric Dad", venue: "Racket", date: "2026-03-10", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/10/saxsquatch-tickets", description: "Electronic music show", price: null },
    { id: "donyc-m10-10", title: "Brooklyn Nets vs. Detroit Pistons", venue: "Barclays Center", date: "2026-03-10", time: "7:30 PM", category: "Sports", sourceUrl: "https://donyc.com/events/2026/3/10/brooklyn-nets-vs-detroit-pistons-tickets", description: "NBA basketball game", price: null },
    { id: "donyc-m10-11", title: "The Drift Presents: A Conversation About the Epstein Files", venue: "The Bell House", date: "2026-03-10", time: "7:30 PM", category: "Talk", sourceUrl: "https://donyc.com/events/2026/3/10/a-conversation-about-the-epstein-files-tickets", description: "Panel discussion", price: null },
    
    // DONYC EVENTS (Source 8) - March 11
    { id: "donyc-m11-1", title: "The Cafe Wha? House Band", venue: "Cafe Wha?", date: "2026-03-11", time: "9:00 PM / 10:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/11/the-cafe-wha-house-band-tickets", description: "Live house band performance", price: null },
    { id: "donyc-m11-2", title: "Eli", venue: "Le Poisson Rouge", date: "2026-03-11", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/11/eli-tickets", description: "Live performance", price: null },
    { id: "donyc-m11-3", title: "Orbit Culture, Ov Sulfur, Atlas", venue: "The Gramercy Theatre", date: "2026-03-11", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/11/orbit-culture-ov-sulfur-atlas-tickets", description: "Metal concert", price: null },
    { id: "donyc-m11-4", title: "Sugar, We're Hoein Down", venue: "3 Dollar Bill", date: "2026-03-11", time: "6:30 PM", category: "Party", sourceUrl: "https://donyc.com/events/2026/3/11/sugar-we-re-hoein-down-tickets", description: "Dance party event", price: null },
    { id: "donyc-m11-5", title: "Dervish", venue: "Sony Hall", date: "2026-03-11", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/11/dervish-tickets", description: "Irish traditional music", price: null },
    { id: "donyc-m11-6", title: "Skaterobics - All Experience Levels", venue: "Xanadu", date: "2026-03-11", time: "6:00 PM", category: "Fitness", sourceUrl: "https://donyc.com/events/2026/3/11/skaterobics-all-experience-levels-instructional-class-tickets", description: "Roller skating instructional class", price: null },
    { id: "donyc-m11-7", title: "Wednesdays on Wheels ft. DJ Dream", venue: "Xanadu", date: "2026-03-11", time: "8:00 PM", category: "Party", sourceUrl: "https://donyc.com/events/2026/3/11/wednesdays-on-wheels-ft-dj-dream-skate-tickets", description: "Roller skating dance party", price: null },
    { id: "donyc-m11-8", title: "Dream, Ivory", venue: "Baby's All Right", date: "2026-03-11", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/11/dream-ivory-tickets", description: "Indie pop performance", price: null },
    { id: "donyc-m11-9", title: "Sun Ra Arkestra", venue: "TV Eye", date: "2026-03-11", time: "6:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/11/sun-ra-arkestra-tickets", description: "Avant-garde jazz", price: null },
    { id: "donyc-m11-10", title: "Glitterer", venue: "The Bowery Ballroom", date: "2026-03-11", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/11/glitterer-tickets", description: "Indie rock show", price: null },
    { id: "donyc-m11-11", title: "Groove Theory The Marcellus Sessions", venue: "Groove", date: "2026-03-11", time: "6:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/weekly/wed/groove-theory-the-marcellus-sessions-tickets", description: "Weekly music series", price: null },
    
    // DONYC EVENTS (Source 8) - March 12
    { id: "donyc-m12-1", title: "John Medeski, Stanton Moore, Nels Cline & Skerik", venue: "Brooklyn Bowl", date: "2026-03-12", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/12/john-medeski-stanton-moore-nels-cline-skerik-tickets", description: "Supergroup jazz/funk performance", price: null },
    { id: "donyc-m12-2", title: "Dan & Peggy Reeder w/ Isaac Stalling", venue: "Le Poisson Rouge", date: "2026-03-12", time: "7:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/12/dan-peggy-reeder-w-isaac-stalling-tickets", description: "Folk/americana performance", price: null },
    { id: "donyc-m12-3", title: "Unbroken Chain: Celebration of Phil Lesh", venue: "The Capitol Theatre", date: "2026-03-12", time: "6:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/12/unbroken-chain-a-celebration-of-the-life-and-music-of-phil-lesh-to-benefit-sweet-relief-tickets", description: "Benefit concert for Sweet Relief", price: null },
    { id: "donyc-m12-4", title: "Redirect 1st Anniversary", venue: "Good Room", date: "2026-03-12", time: "7:00 PM", category: "Party", sourceUrl: "https://donyc.com/events/2026/3/12/redirect-1st-anniversary-kilopatrah-jones-mike-servito-skoglund-bags-tomas-urquieta-hndrnc-erik-braun-tickets", description: "Electronic music anniversary party", price: null },
    { id: "donyc-m12-5", title: "Katatonia - Waking State of North America 2026", venue: "Elsewhere", date: "2026-03-12", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/12/katatonia-tickets", description: "Metal concert with Rivers of Nihil", price: null },
    { id: "donyc-m12-6", title: "Three Days Grace, I Prevail - LOUD ISLAND", venue: "UBS Arena", date: "2026-03-12", time: "6:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/12/three-days-grace-i-prevail-loud-island-bite-bash-tickets", description: "Rock festival", price: null },
    { id: "donyc-m12-7", title: "Concert for Samantha, Claire, and David", venue: "TV Eye", date: "2026-03-12", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/12/concert-for-samantha-claire-and-david-tickets", description: "Benefit concert", price: null },
    { id: "donyc-m12-8", title: "New Joke Night at The Stand", venue: "The Stand", date: "2026-03-12", time: "8:00 PM", category: "Comedy", sourceUrl: "https://donyc.com/events/2026/3/12/new-joke-night-at-the-stand-tickets", description: "New material comedy showcase", price: null },
    { id: "donyc-m12-9", title: "Ethan Lipton & His Orchestra", venue: "Joe's Pub", date: "2026-03-12", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/12/ethan-lipton-his-orchestra-tickets", description: "Theatrical musical performance", price: null },
    
    // DONYC EVENTS (Source 8) - March 13
    { id: "donyc-m13-1", title: "St. Lucia", venue: "White Eagle Hall", date: "2026-03-13", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/st-lucia-tickets", description: "Indie pop in Jersey City", price: null },
    { id: "donyc-m13-2", title: "Jams: A Late 90's + 2000's R&B, Pop, and Hip-Hop Party", venue: "Le Poisson Rouge", date: "2026-03-13", time: "11:00 PM", category: "Party", sourceUrl: "https://donyc.com/events/2026/3/13/jams-a-late-90-s-2000-s-r-b-pop-and-hip-hop-party-tickets", description: "Throwback dance party", price: null },
    { id: "donyc-m13-3", title: "Steve Earle, Margaret Glaspy", venue: "The Gramercy Theatre", date: "2026-03-13", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/steve-earle-tickets", description: "Solo acoustic performance", price: null },
    { id: "donyc-m13-4", title: "Lights: COME GET YOUR GIRL TOUR 2026", venue: "Irving Plaza", date: "2026-03-13", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/lights-come-get-your-girl-tour-2026-tickets", description: "Synth-pop concert", price: null },
    { id: "donyc-m13-5", title: "SunSquabi & Manic Focus", venue: "Brooklyn Bowl", date: "2026-03-13", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/sunsquabi-manic-focus-tickets", description: "Electronic funk/ jam", price: null },
    { id: "donyc-m13-6", title: "Matinee Social Club: Pursuit of Happiness", venue: "Le Poisson Rouge", date: "2026-03-13", time: "6:00 PM", category: "Party", sourceUrl: "https://donyc.com/events/2026/3/13/matinee-social-club-pursuit-of-happiness-tickets", description: "Day party event", price: null },
    { id: "donyc-m13-7", title: "bbno$, jungle bobby", venue: "Terminal 5", date: "2026-03-13", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/bbno-tickets", description: "Rap/hip hop concert", price: null },
    { id: "donyc-m13-8", title: "Okayval", venue: "Music Hall of Williamsburg", date: "2026-03-13", time: "9:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/okayval-tickets", description: "Live performance", price: null },
    { id: "donyc-m13-9", title: "Cut Worms Performance + Signing", venue: "Rough Trade NYC", date: "2026-03-13", time: "6:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/cut-worms-performance-signing-tickets", description: "Free in-store performance", price: "Free" },
    { id: "donyc-m13-10", title: "Cailin Russo", venue: "Mercury Lounge", date: "2026-03-13", time: "6:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/cailin-russo-tickets", description: "Indie pop performance", price: null },
    { id: "donyc-m13-11", title: "Evan Honer, Nicholas Jamerson", venue: "Webster Hall", date: "2026-03-13", time: "6:30 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/13/evan-honer-nicholas-jamerson-tickets", description: "Country/folk performance", price: null },
    
    // DONYC EVENTS (Source 8) - March 14
    { id: "donyc-m14-1", title: "St. Lucia, Performing Two Sets", venue: "Brooklyn Steel", date: "2026-03-14", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/st-lucia-performing-two-sets-tickets", description: "Double set performance", price: null },
    { id: "donyc-m14-2", title: "New Edition with Boyz II Men & Toni Braxton", venue: "Barclays Center", date: "2026-03-14", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/new-edition-tickets", description: "R&B legends concert", price: null },
    { id: "donyc-m14-3", title: "Artemas, Henry Morris, Ellah Boh", venue: "Terminal 5", date: "2026-03-14", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/artemas-isabel-larosa-tickets", description: "Pop concert", price: null },
    { id: "donyc-m14-4", title: "The Rock and Roll Playhouse Plays Music of Coldplay + More for Kids", venue: "Brooklyn Bowl", date: "2026-03-14", time: "12:00 PM", category: "Family", sourceUrl: "https://donyc.com/events/2026/3/14/the-rock-and-roll-playhouse-plays-music-of-coldplay-more-for-kids-tickets", description: "Kids music show", price: null },
    { id: "donyc-m14-5", title: "West Village St. Patrick's Day Bar Fest", venue: "Le Poisson Rouge", date: "2026-03-14", time: "8:00 PM", category: "Party", sourceUrl: "https://donyc.com/events/2026/3/14/west-village-st-patrick-s-day-bar-fest-tickets", description: "St. Paddy's celebration", price: null },
    { id: "donyc-m14-6", title: "HANABIE. - North America Tour 2026", venue: "Brooklyn Bowl", date: "2026-03-14", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/hanabie-north-america-tour-2026-tickets", description: "Japanese metalcore", price: null },
    { id: "donyc-m14-7", title: "Cornelia Murr", venue: "Music Hall of Williamsburg", date: "2026-03-14", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/cornelia-murr-tickets", description: "Indie folk performance", price: null },
    { id: "donyc-m14-8", title: "The Summer Set", venue: "Irving Plaza", date: "2026-03-14", time: "6:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/the-summer-set-tickets", description: "Pop punk concert", price: null },
    { id: "donyc-m14-9", title: "Mike Gordon", venue: "The Stone Pony", date: "2026-03-14", time: "7:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/mike-gordon-tickets", description: "Phish bassist solo show in Asbury Park", price: null },
    { id: "donyc-m14-10", title: "BARELY ALIVE, Tynan, Riddim NYC", venue: "Webster Hall", date: "2026-03-14", time: "11:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/barely-alive-tickets", description: "Dubstep/bass music", price: null },
    { id: "donyc-m14-11", title: "PATTI LABELLE - The 80/65 Tour", venue: "Flagstar at Westbury Music Fair", date: "2026-03-14", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/patti-labelle-the-80-65-tour-tickets", description: "R&B legend concert", price: null },
    { id: "donyc-m14-12", title: "Taiki Nulight - cheeky bugger tour", venue: "The Bowery Ballroom", date: "2026-03-14", time: "8:00 PM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/14/taiki-nulight-cheeky-bugger-tour-tickets", description: "Bass house/UK garage", price: null },
    { id: "donyc-m14-13", title: "Jerrod Carmichael On Stage In Brooklyn", venue: "The Bell House", date: "2026-03-14", time: "8:00 PM", category: "Comedy", sourceUrl: "https://donyc.com/events/2026/3/14/jerrod-carmichael-on-stage-in-brooklyn-tickets", description: "Stand-up comedy", price: null },
    
    // DONYC EVENTS (Source 8) - March 15
    { id: "donyc-m15-1", title: "Burnout Paradise", venue: "Astor Place Theatre", date: "2026-03-15", time: "7:00 PM", category: "Theater", sourceUrl: "https://donyc.com/events/2026/2/18/burnout-paradise-tickets", description: "Theatrical performance", price: null },
    { id: "donyc-m15-2", title: "March Is Music 2026", venue: "Pregones Theater", date: "2026-03-15", time: "7:00 AM", category: "Music", sourceUrl: "https://donyc.com/events/2026/3/1/march-is-music-2026-tickets", description: "Music festival through March 29", price: null },
  ]
};

// Export counts for reporting
const counts = {
  film_museum: {
    metrograph: 22,
    filmForum: 1,
    ifcCenter: 12,
    lincolnCenter: 15,
    theMet: 4,
    moma: 15,
    total: 69
  },
  general: {
    timeOut: 9,
    doNYC: {
      march9: 12,
      march10: 11,
      march11: 11,
      march12: 9,
      march13: 11,
      march14: 13,
      march15: 2,
      total: 69
    },
    total: 78
  }
};

console.log("Film/Museum Events Total:", filmMuseumEvents.events.length);
console.log("General Events Total:", generalEvents.events.length);
console.log("Source Counts:", JSON.stringify(counts, null, 2));

// Write files
const fs = require('fs');
fs.writeFileSync('public/data/film_museum_events.json', JSON.stringify(filmMuseumEvents, null, 2));
fs.writeFileSync('public/data/events.json', JSON.stringify(generalEvents, null, 2));
console.log("Files written successfully!");
